{% set name = "Flask-Babel" %}
{% set version = "0.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 316ad183e42003f3922957fa643d0a1e8e34a0f0301a88c3a8f605bc37ba5c86

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
    - flask
    - babel >=2.3
    - jinja2 >=2.5

  run:
    - python
    - flask
    - babel >=2.3
    - jinja2 >=2.5

test:
  imports:
    - flask_babel

about:
  home: https://github.com/python-babel/flask-babel
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: 'Adds i18n/l10n support to Flask applications'
  dev_url: https://github.com/python-babel/flask-babel

extra:
  recipe-maintainers:
    - pmlandwehr
    - xylar
