{% set name = "Flask-Babel" %}
{% set version = "0.9" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "4afd150f360434b00684ba7848358f7961072fd0658a6e81aaa578522699fb4c" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed --verbose .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - flask
    - babel >=2.3
    - jinja2 >=2.5
    - speaklater >=1.2

test:
  imports:
    - flask_babel

about:
  home: https://github.com/python-babel/flask-babel
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: 'Adds i18n/l10n support to Flask applications'
  dev_url: https://github.com/python-babel/flask-babel

extra:
  recipe-maintainers:
    - pmlandwehr
