{% set name = "Flask-Babel" %}
{% set version = "0.12.2" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "316ad183e42003f3922957fa643d0a1e8e34a0f0301a88c3a8f605bc37ba5c86" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}
  patches:
    fix_werkzeug.patch

build:
  noarch: python
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - m2-patch  # [win]
    - patch     # [not win]
  host:
    - pip
    - python
    - setuptools
    - flask
    - babel >=2.3
    - jinja2 >=2.5

  run:
    - python
    - flask
    - babel >=2.3
    - jinja2 >=2.5

test:
  imports:
    - flask_babel

about:
  home: https://github.com/python-babel/flask-babel
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: 'Adds i18n/l10n support to Flask applications'
  dev_url: https://github.com/python-babel/flask-babel

extra:
  recipe-maintainers:
    - pmlandwehr
