{% set name = "flask-babel" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flask_babel-{{ version }}.tar.gz
  sha256: dbeab4027a3f4a87678a11686496e98e1492eb793cbdd77ab50f4e9a2602a593

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - poetry-core >=1.0.0
  run:
    - python
    - flask >=2.0
    - babel >=2.12
    - jinja2 >=3.1
    - pytz >=2022.7

test:
  imports:
    - flask_babel
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/python-babel/flask-babel
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Adds i18n/l10n support to Flask applications
  description: |
    Flask-Babel is an extension to Flask that adds i18n and l10n support
    to any Flask application with the help of babel, pytz and its own copy of speaklater.
    It has built-in support for date formatting including timezones,
    as well as a very simple and friendly interface to gettext translations.
  dev_url: https://github.com/python-babel/flask-babel
  doc_url: https://python-babel.github.io/flask-babel/

extra:
  recipe-maintainers:
    - pmlandwehr
    - xylar
