travis:
  secure:
    BINSTAR_TOKEN: djzdAwrmG98EU/0mj3ic3+9/NLXMLv7iG5gKQJAcI096h66sKnP+1Fiyh2inYrYD191QnbBbPajftAmPu3eqwm0b/ILrc0fK2DkHcql+mthS8AgiQBa4esQZsRhNZ1JtR7vN/lixVuVLJ3QkAQj49WnN6/mgpsmI6ZarWODt0FH0Dxs+B0oHofraJxIk5uxC9Kn5XIJvGUBD3N/DhI8MAcJc22Rd+ut40qDBq2YPAP+avXwdYRYT+zuKItTXjRKbI2FfuG/RcytB+XombiGSLyzKETqI2MmTiTzJZcGSDhoEfVnGA0NJuoW2i5GoaLhxD7ZNC+RsTgSUGu0pATGT+eV2lfsi3aGC592WjYA1Ha6SGrrzUpWYy6xjhD/zm4u0vdEITSNtH/oA7KR8M8oQbXIH2mc1AoSNoWM1VSlvjZpt54IBSm67JWJuMEsgSTghqbmSks90WdLVaMGs1GRTtRcxGXFMv8F8QUluYGvHnGTCDQ4pKhXEhb/F3C55SsOiZcgZmbMqAxbcR9lC7KnHLOQopcC8yuqM5bntyj4rOjotyB5gix3rj7iKcrIUTSmPpRA15Hz/rx4N/GJjmSYy+oZ5Vdyivvmdx6FuYKl9rZG8+o7JqB4+14V/9wzfl7iKRI/QGl7lx6CjQ9FGcbwudhcT/SEMCU/TD5x7zFGKFzU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
