travis:
  secure:
    BINSTAR_TOKEN: l6FI9Lqu4ubr7bjm4Sce1+KNx2Y+fuzr894CuW3YazHfFeE1sTq6aLUZYU/BrfyjHAu86yUUr6Da7zmM2f4Jbtl4HTMiLVX8uGTrO2E0pHMpfYpZx/8elVI2Rwv2LSXCXwMCHVlKI6iCoxoyoR94LNdNPecyKslmSyHvAMHx/F9Z5CvvLM5W+CwXcRef23tmzCirrnlP1t1B88lySOexmpH7t+xpueVxHnBgdcZAT70THGbT416jIMtcdi43TLRlTerOrJ8Vo4UtAxMWL9tNl8+cU5RdWrIEVhNPbF5y2Zh4GVOpjfC7KYng2pu8AXMcUkWCEi1P8fjE1JE2VHyqf+LIX1T30KNEnUM2pN9wn+WA2YekobNvDGRJR3Agnls4k9mnDFvL2TpOsTr5t4nUvADfHgSShtjfZ/Zf0oHZnT2J0jNP3sGSxUGUyl5FuCwUxBMK363Riy8MqAeabFWqs3LgK3wT3iDEYGZFrlRuQkmb1klY2ZU63Ggj4DAG5+KD98zEitCl+Fc8rvaI/m4msY2q7SIieo/RN4+r3hhB8WVJ3C+AaFw1VLAFdPppDWVzPxHURgGBRzz1i0l2a2xjsRx9wtJYiIQKtRZSVw6nuYBNDDlEsC5T8IFvS07P07rnV9/a2o0SVAkkuDFiiEG5Tf/FVNn+QJA35oWttOZfR0c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
